% Define images to process
imageFileNames = {'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\0L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\1L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\2L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\3L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\4L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\5L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\6L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\7L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\8L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\9L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\10L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\11L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\12L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\13L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\14L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\15L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\16L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\17L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\18L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\19L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\20L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\21L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\22L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\23L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\24L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\25L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\26L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\27L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\28L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\29L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\30L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\31L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\32L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\33L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\34L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\35L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\36L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\37L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\38L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\39L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\40L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\41L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\42L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\43L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\44L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\45L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\47L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\48L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\49L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\50L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\51L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\52L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\53L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\54L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\57L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\58L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\59L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\60L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\61L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\62L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\63L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\64L.png',...
    'C:\Users\luka\Desktop\MasterOfScienceProject\calib\calib\65L.png',...
    };
% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Read the first image to obtain image size
originalImage = imread(imageFileNames{1});
[mrows, ncols, ~] = size(originalImage);

% Generate world coordinates of the corners of the squares
squareSize = 40;  % in units of 'millimeters'
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

% View reprojection errors
h1=figure; showReprojectionErrors(cameraParams);

% Visualize pattern locations
h2=figure; showExtrinsics(cameraParams, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, cameraParams);

% For example, you can use the calibration data to remove effects of lens distortion.
undistortedImage = undistortImage(originalImage, cameraParams);


